#!/bin/bash
set -e
export me="$(test -L "$0" && readlink "$0" || echo "$0")"
eval "$("$(dirname "$me")"/adr-config)"

cmd=$adr_bin_dir/adr-$1

if [ -x $cmd ]
then
    $cmd "${@:2}"
else
    $adr_bin_dir/adr-help
    exit 1
fi
